CREATE TABLE albumlist (albumid text PRIMARY KEY,name text,"desc" text,createtime timestamp,lastuploadtime timestamp,modifytime timestamp,total integer);
CREATE TABLE blogcmt (blogid integer,cmtid integer,posterid integer,content text,posttime timestamp,replynum integer,PRIMARY KEY (blogid,cmtid));
CREATE TABLE bloglist (blogid integer PRIMARY KEY,cate text,title text,pubtime timestamp,cmtnum integer);
CREATE TABLE blogreply (blogid integer,cmtid integer,rplid integer,posterid text,content text,posttime timestamp,PRIMARY KEY (blogid,cmtid,rplid));
CREATE TABLE msgboard (cmtid integer PRIMARY KEY,uin integer,content text,pubtime timestamp,modifytime timestamp,replynum integer);
CREATE TABLE msgreply (cmtid integer,rplid integer,uin integer,content text,"time" timestamp,PRIMARY KEY (cmtid,rplid));
CREATE TABLE photocmt (albumid text,photoid text,cmtid integer,posterid integer,content text,posttime timestamp,replynum integer,PRIMARY KEY (albumid,photoid,cmtid));
CREATE TABLE photolist (albumid text,photoid text,name text,"desc" text,uploadtime timestamp,cmtnum integer,PRIMARY KEY (albumid,photoid));
CREATE TABLE photoreply (albumid text,photoid text,cmtid integer,rplid integer,posterid integer,content text,posttime timestamp,PRIMARY KEY (albumid,photoid,cmtid,rplid));
CREATE TABLE sscmt (ssid text,cmtid integer,uin integer,content text,createtime timestamp,replynum integer,PRIMARY KEY (ssid,cmtid));
CREATE TABLE sslist (ssid text PRIMARY KEY,content text,createtime timestamp,cmtnum integer);
CREATE TABLE ssreply (ssid text,cmtid integer,rplid integer,uin integer,content text,createtime timestamp,PRIMARY KEY (ssid,cmtid,rplid));
